name: dataviz
favicon: null
layout_spectrum: 0.3845474566332996
typography_spectrum: 0.3052827110514045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3509515377227217
  lightness: 0.4761102960910648
  saturation: 0.26494960486888885
  rhythmicContrast: 0.9695224384777248
purpose: []
